---
title: "Viz Homework"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
hd <- read_csv("Data/heart_disease.csv")
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
p <- ggplot(hd, aes(x = age, y = trestbps))
p + geom_smooth(size = 2)

```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
p <- ggplot(hd, aes(x = trestbps, y = chol))
p + geom_point(aes(color = outcome), size = 2, pch = 4)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
p <- ggplot(hd, aes(thalach, chol)) 
p + geom_smooth() + geom_point(aes(color = outcome)) + facet_wrap(~cp, ncol = 4)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
p <- ggplot(filter(hd,cp > 1 & cp < 4), aes(thalach, chol)) 
p + geom_smooth() + geom_point(aes(color = outcome)) + facet_wrap(~cp, ncol = 1)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
p <- ggplot(hd, aes(x = outcome, y = age)) 
p + geom_boxplot() + geom_jitter(aes(color = sex)) + ggtitle("Age vs. Outcome by Sex") +  xlab("Heart Disease Outcome") + ylab("Age (years)")
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
hd$cp <- as.factor(hd$cp)
p <- ggplot(hd, aes(thalach))
p + geom_density(aes(color = cp, fill = cp), alpha = 1/4) + geom_vline(xintercept = c(100, 150), size = 2, color = c("firebrick", "blue"), alpha = 1/4) + geom_hline(yintercept = c(.005, .020), size = 3, color = c("green", "yellow"), alpha = 1/4) + xlab("Maximum Heart Rate Achieved") + ggtitle("Distribution of Maximum Heart Rate Achieved by Chest Pain Type")

```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
p <- ggplot(hd, aes(thalach))
p + geom_density(aes(color = cp, fill = cp)) + xlab("Maximum Heart Rate Achieved") + ggtitle("Distribution of Maximum Heart Rate Achieved by Chest Pain Type") + facet_wrap(aes(cp))
```
